# Identifying the Best Match for Earth for a possible habitable planet

In [1]:
# importing
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter
import warnings
warnings.filterwarnings('ignore')

In [2]:
# loading dataset
dataset = pd.read_csv('filtered_exoplanet_dataset_removed_outliers.csv')

In [3]:
dataset

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,324.620000,1.226000,NaN,NaN,5505.066163,17.321333,0.234500,NaN,G8 III,4808.000000,16.380000,2.463333,93.1846,2.3800,17.793252,Radial Velocity
1,11 UMi b,11 UMi,516.219985,1.526667,NaN,NaN,3818.094733,12.013333,0.080000,NaN,K4 III,4276.500000,26.935000,2.093333,125.3210,1.7650,71.823943,Radial Velocity
2,14 And b,14 And,186.300000,0.761667,NaN,NaN,1224.550433,3.853000,0.000000,NaN,K0 III,4850.500000,11.275000,1.726667,75.4392,2.5900,39.235837,Radial Velocity
3,14 Her b,14 Her,1766.378417,2.814750,NaN,NaN,1642.383591,5.167625,0.362925,NaN,K0 V,5296.985000,0.976667,0.927143,17.9323,4.4200,43.816362,Radial Velocity
4,16 Cyg B b,16 Cyg B,799.375000,1.662833,NaN,NaN,533.514528,1.678667,0.676033,NaN,G2.5 V,5728.594000,1.140000,1.016000,21.1397,4.3440,50.516824,Radial Velocity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5625,ups And b,ups And,4.616229,0.058895,NaN,NaN,219.960419,0.692086,0.030200,NaN,F8 V,6137.820000,1.615000,1.250000,13.4054,4.1625,41.403815,Radial Velocity
5626,ups And c,ups And,240.728533,0.827712,NaN,NaN,1275.328758,4.012667,0.238933,NaN,F8 V,6117.093333,1.615000,1.262500,13.4054,4.1500,41.403815,Radial Velocity
5627,ups And d,ups And,1285.346167,2.528382,NaN,NaN,1616.242590,5.085333,0.281117,NaN,F8 V,6117.093333,1.615000,1.262500,13.4054,4.1500,41.403815,Radial Velocity
5628,ups Leo b,ups Leo,385.200000,1.180000,NaN,NaN,162.092490,0.510000,0.320000,NaN,G9 III,4836.000000,11.220000,1.480000,52.5973,2.4600,-0.823564,Radial Velocity
5629,xi Aql b,xi Aql,136.860000,0.628333,NaN,NaN,716.301647,2.253667,0.029500,NaN,K0 III,4810.500000,11.430000,1.780000,56.1858,2.6350,8.461105,Radial Velocity

In [4]:
# display kepler-452 b
dataset[dataset['planet_name'] == 'Kepler-452 b']

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
3999,Kepler-452 b,Kepler-452,384.844831,1.009733,1.3722,0.138,NaN,NaN,0.0,235.0,G2,5687.166667,0.998333,0.97,551.727,4.446,44.277586,Transit

In [5]:
# manually setting the mass for kepler-452 b
kepler452b_mass = 3.29  # in Earth mass
dataset.loc[dataset['planet_name'] == 'Kepler-452 b', 'planet_mass_earth_mass'] = kepler452b_mass

In [6]:
# display kepler-452 b to see if the mass was included
dataset[dataset['planet_name'] == 'Kepler-452 b']

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
3999,Kepler-452 b,Kepler-452,384.844831,1.009733,1.3722,0.138,3.29,NaN,0.0,235.0,G2,5687.166667,0.998333,0.97,551.727,4.446,44.277586,Transit

In [7]:
# removing exoplanets which are not orbiting a main sequence star, sub giant, or red giant
# WILL EDIT ONCE FINAL DATASET COMPLETE
dataset = dataset[dataset.iloc[:,0] != 'NN Ser c']
dataset = dataset[dataset.iloc[:,0] != 'NN Ser d']
dataset = dataset[dataset.iloc[:,0] != 'CFBDSIR J145829+101343 b']
dataset = dataset[dataset.iloc[:,0] != 'WISE J033605.05-014350.4 b']
dataset = dataset[dataset.iloc[:,0] != 'WISEP J121756.91+162640.2 A b']

### Filtering exoplanets to only include those which are orbiting a sun-like (Type G) star

In [8]:
# filling in the missing values for the spectral type column with unknown to allow for filtering computation
# WILL EDIT ONCE FINAL DATASET DONE
dataset['spectral_type'].fillna('Unknown', inplace=True)

dataset.head(20)

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,324.620000,1.226000,NaN,NaN,5505.066163,17.321333,0.234500,NaN,G8 III,4808.000,16.380000,2.463333,93.1846,2.380,17.793252,Radial Velocity
1,11 UMi b,11 UMi,516.219985,1.526667,NaN,NaN,3818.094733,12.013333,0.080000,NaN,K4 III,4276.500,26.935000,2.093333,125.3210,1.765,71.823943,Radial Velocity
2,14 And b,14 And,186.300000,0.761667,NaN,NaN,1224.550433,3.853000,0.000000,NaN,K0 III,4850.500,11.275000,1.726667,75.4392,2.590,39.235837,Radial Velocity
3,14 Her b,14 Her,1766.378417,2.814750,NaN,NaN,1642.383591,5.167625,0.362925,NaN,K0 V,5296.985,0.976667,0.927143,17.9323,4.420,43.816362,Radial Velocity
4,16 Cyg B b,16 Cyg B,799.375000,1.662833,NaN,NaN,533.514528,1.678667,0.676033,NaN,G2.5 V,5728.594,1.140000,1.016000,21.1397,4.344,50.516824,Radial Velocity
5,17 Sco b,17 Sco,578.380000,1.450000,NaN,NaN,1373.018720,4.320000,0.060000,NaN,K3 III,4157.000,25.920000,1.220000,124.9530,1.700,-11.837791,Radial Velocity
6,18 Del b,18 Del,988.075000,2.538667,NaN,NaN,3109.015380,9.782333,0.052000,NaN,G6 III,4979.500,8.650000,2.166667,76.2220,2.845,10.839138,Radial Velocity
7,1RXS J160929.1-210524 b,1RXS J160929.1-210524,NaN,330.000000,18.647,1.664,3135.750000,9.000000,NaN,1750.0,K7 V,4043.250,1.330000,0.792500,139.1350,4.000,-21.083140,Imaging
8,24 Boo b,24 Boo,30.340300,0.192000,NaN,NaN,284.933890,0.896500,0.037000,NaN,G3 IV,4854.500,11.415000,1.020000,95.9863,2.350,49.844649,Radial Velocity
9,24 Sex b,24 Sex,452.800000,1.333000,NaN,NaN,632.460000,1.990000,0.090000,NaN,Unknown,5098.000,4.900000,1.540000,72.0691,3.500,-0.902400,Radial Velocity
10,24 Sex c,24 Sex,883.000000,2.080000,NaN,NaN,273.320000,0.860000,0.290000,NaN,Unknown,5098.000,4.900000,1.540000,72.0691,3.500,-0.902400,Radial Velocity
11,2M0437 b,2MASS J04372171+2651014,NaN,118.000000,NaN,NaN,1271.313630,4.000000,NaN,1450.0,M V,3100.000,0.840000,0.170000,128.4840,4.500,26.850300,Imaging
12,2MASS J01033563-5515561 AB b,2MASS J01033563-5515561 A,NaN,84.000000,NaN,NaN,4131.790000,13.000000,NaN,NaN,M5.5/M6,NaN,NaN,0.190000,NaN,NaN,-55.265829,Imaging
13,2MASS J01225093-2439505 b,2MASS J01225093-2439505,NaN,52.000000,11.209,1.000,7786.500000,24.500000,NaN,1600.0,M3.5 V,3419.500,0.370000,0.375000,33.8281,4.860,-24.664613,Imaging
14,2MASS J02192210-3925225 b,2MASS J02192210-3925225,NaN,156.000000,16.141,1.440,4417.837000,13.900000,NaN,NaN,M6,3064.000,0.280000,0.110000,NaN,4.590,-39.423077,Imaging
15,2MASS J0249-0557 c,2MASS J0249-0557 A,NaN,1950.000000,NaN,NaN,3686.809520,11.600000,NaN,NaN,M6 V,NaN,NaN,0.050000,66.0613,NaN,-5.959992,Imaging
16,2MASS J03590986+2009361 b,2MASS J03590986+2009361,NaN,572.000000,NaN,NaN,5720.911330,18.000000,NaN,2369.0,Unknown,NaN,NaN,NaN,117.4350,NaN,20.159976,Imaging
17,2MASS J04414489+2301513 b,2MASS J04414489+2301513,NaN,15.000000,NaN,NaN,2383.600000,7.500000,NaN,NaN,M8.5,NaN,NaN,0.020000,NaN,NaN,23.030854,Imaging
18,2MASS J11011926-7732383 b,2MASS J11011926-7732383,NaN,266.000000,NaN,NaN,8899.195400,28.000000,NaN,2677.0,Unknown,NaN,NaN,NaN,NaN,NaN,-77.544091,Imaging
19,2MASS J11550485-7919108 b,2MASS J11550485-7919108,NaN,587.000000,NaN,NaN,6356.568140,20.000000,NaN,2506.0,Unknown,NaN,NaN,NaN,100.8620,NaN,-79.319756,Imaging

In [9]:
# filtering exoplanets to only include those which are orbiting a sun-like (Type G) star
filtered_dataset = dataset[dataset['spectral_type'].str.startswith('G')]

filtered_dataset

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,324.620000,1.226000,NaN,NaN,5505.066163,17.321333,0.234500,NaN,G8 III,4808.000000,16.380000,2.463333,93.1846,2.380000,17.793252,Radial Velocity
4,16 Cyg B b,16 Cyg B,799.375000,1.662833,NaN,NaN,533.514528,1.678667,0.676033,NaN,G2.5 V,5728.594000,1.140000,1.016000,21.1397,4.344000,50.516824,Radial Velocity
6,18 Del b,18 Del,988.075000,2.538667,NaN,NaN,3109.015380,9.782333,0.052000,NaN,G6 III,4979.500000,8.650000,2.166667,76.2220,2.845000,10.839138,Radial Velocity
8,24 Boo b,24 Boo,30.340300,0.192000,NaN,NaN,284.933890,0.896500,0.037000,NaN,G3 IV,4854.500000,11.415000,1.020000,95.9863,2.350000,49.844649,Radial Velocity
27,47 UMa b,47 UMa,1083.040000,2.095800,NaN,NaN,812.223832,2.555600,0.041200,NaN,G0 V,5861.053333,1.175000,1.043333,13.7967,4.315000,40.430493,Radial Velocity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5612,pi Men c,HD 39091,6.267966,0.068137,2.051,0.183,4.116528,0.012953,0.019250,1158.5,G0 V,5943.750000,1.122500,1.060000,18.2702,4.380000,-80.464604,Transit
5614,psi1 Dra B b,psi1 Dra B,3117.000000,4.430000,NaN,NaN,486.279900,1.530000,0.400000,NaN,G0 V,6212.000000,NaN,1.190000,22.7188,4.200000,72.155711,Radial Velocity
5615,rho CrB b,rho CrB,39.794460,0.223850,NaN,NaN,341.261020,1.073725,0.034700,614.0,G0 V,5747.827500,1.342500,0.937500,17.4671,4.166667,33.300186,Radial Velocity
5616,rho CrB c,rho CrB,102.429000,0.416200,NaN,NaN,27.109270,0.085297,0.064000,448.0,G0 V,5738.103333,1.353333,0.916667,17.4671,4.166667,33.300186,Radial Velocity
5628,ups Leo b,ups Leo,385.200000,1.180000,NaN,NaN,162.092490,0.510000,0.320000,NaN,G9 III,4836.000000,11.220000,1.480000,52.5973,2.460000,-0.823564,Radial Velocity

In [10]:
# checking if kepler-452 b is present
kepler_452b_present = 'Kepler-452 b' in filtered_dataset['planet_name'].values
print(f"Is Kepler-452 b in the filtered dataset? {kepler_452b_present}")

Is Kepler-452 b in the filtered dataset? True

### Filtering based on mass and radius relation to see if Earth like and/or Super-Earth like

In [11]:
# Creating condition for Earth like and Super Earth like together
earth_and_super_earth_condition = (filtered_dataset['planet_rad_earth_rad'] <= 2) & (filtered_dataset['planet_mass_earth_mass'] <= 8)

# applying condtion to filtered dataset
filtered_dataset2 = filtered_dataset[earth_and_super_earth_condition]

# displaying filtered dataset
filtered_dataset2

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
120,CoRoT-7 b,CoRoT-7,0.853629,0.017023,1.652500,0.147333,7.249359,0.022806,0.030000,1833.000000,G9 V,5266.750000,0.862857,0.892500,159.9060,4.510000,-1.063008,Transit
624,HD 136352 b,HD 136352,11.579387,0.095567,1.573000,0.140000,4.716667,0.014830,0.073000,908.000000,G4 V,5726.000000,1.035000,0.863333,14.6820,4.386667,-48.318817,Radial Velocity
631,HD 137496 b,HD 137496,1.621160,0.027320,1.310000,0.117000,4.040000,0.012710,0.000000,2130.000000,G,5799.000000,1.590000,1.040000,155.3170,4.050000,-16.509001,Transit
1174,HD 80653 b,HD 80653,0.719581,0.016605,1.613000,0.144000,5.660000,0.017810,0.000000,2463.000000,G2,6019.500000,1.220000,1.180000,109.8600,4.340000,14.367869,Transit
1218,HD 93963 A b,HD 93963 A,1.039135,0.020850,1.350000,0.120000,7.800000,0.024540,NaN,2042.000000,G0 V,5987.000000,1.040000,1.110000,82.3432,4.490000,25.641065,Transit
1352,K2-111 b,K2-111,5.351605,0.058533,1.710500,0.152500,6.490000,0.020420,0.076667,1309.000000,G2,5761.800000,1.181667,0.860000,200.3940,4.245000,21.298526,Transit
1385,K2-138 b,K2-138,2.353173,0.033817,1.523333,0.136000,3.100000,0.009750,0.225500,1157.000000,G8 V,5339.100000,0.853333,0.930000,202.5850,4.556667,-10.849739,Transit
1567,K2-265 b,K2-265,2.368974,0.033760,1.658400,0.148400,6.540000,0.020580,0.084000,NaN,G8 V,5424.400000,0.905000,0.930000,138.6710,4.467500,-14.494779,Transit
1999,Kepler-101 c,Kepler-101,6.029708,0.067486,1.076556,0.107500,3.780000,0.010000,0.000000,1145.666667,G3 IV,5655.104000,1.421000,1.087500,927.9810,4.204444,48.355247,Transit
3999,Kepler-452 b,Kepler-452,384.844831,1.009733,1.372200,0.138000,3.290000,NaN,0.000000,235.000000,G2,5687.166667,0.998333,0.970000,551.7270,4.446000,44.277586,Transit
4441,Kepler-78 b,Kepler-78,0.355006,0.009010,1.183286,0.105571,2.691023,0.008464,0.000000,2236.500000,G,5087.477143,0.742857,0.810000,124.3760,4.601667,44.448252,Transit
5046,TOI-1416 b,TOI-1416,1.069757,0.019000,1.620000,0.145000,3.480000,0.010950,0.000000,1517.000000,G9 V,4884.000000,0.790000,0.800000,55.0135,4.520000,41.952986,Transit
5286,TOI-561 b,TOI-561,0.446572,0.010597,1.417000,0.126250,2.257500,0.007103,0.000000,2395.000000,G9 V,5369.750000,0.837500,0.805000,85.7990,4.492500,6.216103,Transit
5311,TOI-733 b,TOI-733,4.884765,0.061800,1.992000,0.178000,5.720000,0.018000,0.046000,1056.000000,G,5585.000000,0.950000,0.960000,75.2092,4.470000,-40.888259,Transit

In [12]:
# checking if kepler-452 b is present
kepler_452b_present = 'Kepler-452 b' in filtered_dataset2['planet_name'].values
print(f"Is Kepler-452 b in the filtered dataset? {kepler_452b_present}")

Is Kepler-452 b in the filtered dataset? True

### Filtering based on the Distance between Exoplanet and its Host Star

In [13]:
# creating condition (lower limit 0.75 AU and upper limit 1.5 AU)
orbit_semi_major_axis_condtion = (filtered_dataset2['orbit_semi_major_axis_au'] >= 0.75) & (filtered_dataset2['orbit_semi_major_axis_au'] <= 1.5)

# applying condtion to latest filtered dataset
filtered_dataset3 = filtered_dataset2[orbit_semi_major_axis_condtion]

# displaying latest filtered datset
filtered_dataset3

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
3999,Kepler-452 b,Kepler-452,384.844831,1.009733,1.3722,0.138,3.29,NaN,0.0,235.0,G2,5687.166667,0.998333,0.97,551.727,4.446,44.277586,Transit

### Filtering Vased on the Orbital Period

In [14]:
# creating condition (for a G like star this is the habital zone where the lower limit of 200 Earth days is venus and upper limit of 700 Earth days is mars)
orbital_period_condtion = (filtered_dataset3['orbital_period_day'] >= 200) & (filtered_dataset3['orbital_period_day'] <= 700)

# applying condtion to latest filtered dataset
filtered_dataset4 = filtered_dataset3[orbital_period_condtion]

# displaying latest filtered datset
filtered_dataset4

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
3999,Kepler-452 b,Kepler-452,384.844831,1.009733,1.3722,0.138,3.29,NaN,0.0,235.0,G2,5687.166667,0.998333,0.97,551.727,4.446,44.277586,Transit