# Updated Exoplanet Dataset Analysis

### Creating a Program to Filter and Clean Updated Exoplanet Dataset - Samia Mahmood

In [305]:
# Importing
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Loading and viewing dataset

In [306]:
# loading dataset
dataset = pd.read_csv('Updated ExoplanetData.csv')

In [307]:
dataset.head(10)

,planet_name,host_star_name,num_of_stars,num_of_planets,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,...,stellar_metallicity_ratio,stellar_surf_grav,declination_deg,discovery_method,discovery_year,last_update_date,ref_pub_date,solution_type,Unnamed: 26,discovery_facility
0,11 Com b,11 Com,2,1,NaN,1.210,NaN,NaN,5434.70000,17.100,...,NaN,NaN,17.793252,Radial Velocity,2007,7/23/2014,2011-08,Published Confirmed,NaN,Xinglong Station
1,11 Com b,11 Com,2,1,326.03000,1.290,NaN,NaN,6165.60000,19.400,...,[Fe/H],2.31,17.793252,Radial Velocity,2007,5/14/2014,2008-01,Published Confirmed,NaN,Xinglong Station
2,11 Com b,11 Com,2,1,323.21000,1.178,NaN,NaN,4914.89849,15.464,...,[Fe/H],2.45,17.793252,Radial Velocity,2007,9/19/2023,2023-08,Published Confirmed,NaN,Xinglong Station
3,11 UMi b,11 UMi,1,1,516.21997,1.530,NaN,NaN,4684.81420,14.740,...,[Fe/H],1.93,71.823943,Radial Velocity,2009,9/4/2018,2017-03,Published Confirmed,NaN,Thueringer Landessternwarte Tautenburg
4,11 UMi b,11 UMi,1,1,NaN,1.510,NaN,NaN,3432.40000,10.800,...,NaN,NaN,71.823943,Radial Velocity,2009,4/25/2018,2011-08,Published Confirmed,NaN,Thueringer Landessternwarte Tautenburg
5,11 UMi b,11 UMi,1,1,516.22000,1.540,NaN,NaN,3337.07000,10.500,...,[Fe/H],1.60,71.823943,Radial Velocity,2009,4/25/2018,2009-10,Published Confirmed,NaN,Thueringer Landessternwarte Tautenburg
6,14 And b,14 And,1,1,186.76000,0.775,NaN,NaN,1131.15130,3.559,...,[Fe/H],2.55,39.235837,Radial Velocity,2008,9/19/2023,2023-08,Published Confirmed,NaN,Okayama Astrophysical Observatory
7,14 And b,14 And,1,1,NaN,0.680,NaN,NaN,1017.00000,3.200,...,NaN,NaN,39.235837,Radial Velocity,2008,7/23/2014,2011-08,Published Confirmed,NaN,Okayama Astrophysical Observatory
8,14 And b,14 And,1,1,185.84000,0.830,NaN,NaN,1525.50000,4.800,...,[Fe/H],2.63,39.235837,Radial Velocity,2008,5/14/2014,2008-12,Published Confirmed,NaN,Okayama Astrophysical Observatory
9,14 Her b,14 Her,1,2,1773.40000,2.770,NaN,NaN,1474.67000,4.640,...,NaN,NaN,43.816362,Radial Velocity,2002,4/25/2018,2007-01,Published Confirmed,NaN,W. M. Keck Observatory

In [308]:
dataset.tail(10)

,planet_name,host_star_name,num_of_stars,num_of_planets,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,...,stellar_metallicity_ratio,stellar_surf_grav,declination_deg,discovery_method,discovery_year,last_update_date,ref_pub_date,solution_type,Unnamed: 26,discovery_facility
35954,ups And d,ups And,2,3,1282.410,2.51700,NaN,NaN,1303.09647,4.100,...,[Fe/H],4.13,41.403815,Radial Velocity,1999,9/20/2021,2021-05,Published Confirmed,NaN,Multiple Observatories
35955,ups And d,ups And,2,3,1281.507,2.53000,NaN,NaN,3257.74117,10.250,...,[Fe/H],4.25,41.403815,Radial Velocity,1999,8/3/2021,2010-06,Published Confirmed,NaN,Multiple Observatories
35956,ups And d,ups And,2,3,1278.100,2.53000,NaN,NaN,1312.63790,4.130,...,[M/H],4.07,41.403815,Radial Velocity,1999,4/24/2015,2009-03,Published Confirmed,NaN,Multiple Observatories
35957,ups And d,ups And,2,3,1276.460,2.51329,NaN,NaN,1313.22000,4.132,...,NaN,NaN,41.403815,Radial Velocity,1999,1/28/2019,2011-01,Published Confirmed,NaN,Multiple Observatories
35958,ups And d,ups And,2,3,1274.600,2.51000,NaN,NaN,1255.38000,3.950,...,NaN,NaN,41.403815,Radial Velocity,1999,9/18/2014,2007-01,Published Confirmed,NaN,Multiple Observatories
35959,ups And d,ups And,2,3,1319.000,2.57000,NaN,NaN,1255.38000,3.950,...,NaN,NaN,41.403815,Radial Velocity,1999,8/21/2014,2004-01,Published Confirmed,NaN,Multiple Observatories
35960,ups Leo b,ups Leo,1,1,385.200,1.18000,NaN,NaN,162.09249,0.510,...,[Fe/H],2.46,-0.823564,Radial Velocity,2021,1/10/2022,2021-12,Published Confirmed,NaN,Okayama Astrophysical Observatory
35961,xi Aql b,xi Aql,1,1,NaN,0.58000,NaN,NaN,642.00000,2.020,...,NaN,NaN,8.461105,Radial Velocity,2007,7/23/2014,2011-08,Published Confirmed,NaN,Okayama Astrophysical Observatory
35962,xi Aql b,xi Aql,1,1,136.750,0.68000,NaN,NaN,890.00000,2.800,...,[Fe/H],2.66,8.461105,Radial Velocity,2007,5/14/2014,2008-06,Published Confirmed,NaN,Okayama Astrophysical Observatory
35963,xi Aql b,xi Aql,1,1,136.970,0.62500,NaN,NaN,616.90494,1.941,...,[Fe/H],2.61,8.461105,Radial Velocity,2007,9/19/2023,2023-08,Published Confirmed,NaN,Okayama Astrophysical Observatory

In [309]:
# looking at information about dataset
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35964 entries, 0 to 35963
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   planet_name                35964 non-null  object
 1   host_star_name             35964 non-null  object
 2   num_of_stars               35964 non-null  int64
 3   num_of_planets             35964 non-null  int64
 4   orbital_period_day         32854 non-null  float64
 5   orbit_semi_major_axis_au   19736 non-null  float64
 6   planet_rad_earth_rad       24449 non-null  float64
 7   planet_rad_jup_rad         11331 non-null  float64
 8   planet_mass_earth_mass     5902 non-null   float64
 9   planet_mass_jup_mass       5901 non-null   float64
 10  Eccentricity               17997 non-null  float64
 11  planet_equil_temp_k        16227 non-null  float64
 12  spectral_type              2574 non-null   object
 13  stellar_effective_temp_k   33081 non-null  float64
 14  stellar_rad_solar_rad      33110 non-null  float64
 15  stellar_mass_solar_mass    30410 non-null  float64
 16  distance_parsec            35133 non-null  float64
 17  stellar_metallicity        22564 non-null  float64
 18  stellar_metallicity_ratio  22367 non-null  object
 19  stellar_surf_grav          29308 non-null  float64
 20  declination_deg            35964 non-null  float64
 21  discovery_method           35964 non-null  object
 22  discovery_year             35964 non-null  int64
 23  last_update_date           35963 non-null  object
 24  ref_pub_date               35964 non-null  object
 25  solution_type              35964 non-null  object
 26  Unnamed: 26                0 non-null      float64
 27  discovery_facility         35964 non-null  object
dtypes: float64(16), int64(3), object(9)
memory usage: 7.7+ MB

In [310]:
# looking at statistics about dataset
dataset.describe()

,num_of_stars,num_of_planets,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_metallicity,stellar_surf_grav,declination_deg,discovery_year,Unnamed: 26
count,35964.000000,35964.000000,3.285400e+04,19736.000000,24449.000000,11331.000000,5902.000000,5901.000000,17997.000000,16227.000000,33081.000000,33110.000000,30410.000000,35133.000000,22564.000000,29308.000000,35964.000000,35964.000000,0.0
mean,1.085530,1.884551,1.328807e+04,3.174328,5.287643,0.432290,753.171185,2.370164,0.043391,874.849510,5465.072012,1.154935,0.943807,732.518348,-0.027943,4.410806,32.265102,2015.320237,NaN
std,0.309859,1.205548,2.219136e+06,94.366226,69.927688,0.470498,1445.061164,4.546884,0.122625,424.528913,1007.618494,1.841809,0.322816,787.354452,0.229536,0.294813,27.287976,3.815719,NaN
min,1.000000,1.000000,9.070629e-02,0.004400,0.270000,0.025000,0.015000,0.000050,0.000000,34.000000,415.000000,0.010000,0.000000,1.301190,-2.500000,0.540000,-88.121111,1992.000000,NaN
25%,1.000000,1.000000,4.378080e+00,0.054200,1.550000,0.150000,18.416405,0.058090,0.000000,566.000000,5098.000000,0.790000,0.810000,297.462000,-0.160000,4.310000,38.384092,2014.000000,NaN
50%,1.000000,1.000000,1.035742e+01,0.101000,2.280000,0.226000,225.659300,0.710000,0.000000,794.000000,5613.000000,0.950000,0.960000,601.629000,-0.013000,4.470000,42.657789,2016.000000,NaN
75%,1.000000,2.000000,2.680530e+01,0.219700,3.226000,0.460000,729.934420,2.300000,0.000000,1095.000000,5953.000000,1.210000,1.070000,945.775000,0.120000,4.570000,46.640168,2016.000000,NaN
max,4.000000,8.000000,4.020000e+08,7506.000000,4282.980000,8.102000,25426.400000,80.000000,0.970000,4050.000000,57000.000000,88.470000,23.560000,8800.000000,7.790000,7.920000,85.736533,2024.000000,NaN

In [311]:
# looking at number of rows and columns for dataset
dataset.shape #35,964 rows and 28 columns

(35964, 28)

In [312]:
# column names of dataset
dataset.columns

Index(['planet_name', 'host_star_name', 'num_of_stars', 'num_of_planets',
       'orbital_period_day', 'orbit_semi_major_axis_au',
       'planet_rad_earth_rad', 'planet_rad_jup_rad', 'planet_mass_earth_mass',
       'planet_mass_jup_mass', 'Eccentricity', 'planet_equil_temp_k',
       'spectral_type', 'stellar_effective_temp_k', 'stellar_rad_solar_rad',
       'stellar_mass_solar_mass', 'distance_parsec', 'stellar_metallicity',
       'stellar_metallicity_ratio', 'stellar_surf_grav', 'declination_deg',
       'discovery_method', 'discovery_year', 'last_update_date',
       'ref_pub_date', 'solution_type', 'Unnamed: 26', 'discovery_facility'],
      dtype='object')

In [313]:
# checking for null (missing) values
dataset.isna().sum()

planet_name                      0
host_star_name                   0
num_of_stars                     0
num_of_planets                   0
orbital_period_day            3110
orbit_semi_major_axis_au     16228
planet_rad_earth_rad         11515
planet_rad_jup_rad           24633
planet_mass_earth_mass       30062
planet_mass_jup_mass         30063
Eccentricity                 17967
planet_equil_temp_k          19737
spectral_type                33390
stellar_effective_temp_k      2883
stellar_rad_solar_rad         2854
stellar_mass_solar_mass       5554
distance_parsec                831
stellar_metallicity          13400
stellar_metallicity_ratio    13597
stellar_surf_grav             6656
declination_deg                  0
discovery_method                 0
discovery_year                   0
last_update_date                 1
ref_pub_date                     0
solution_type                    0
Unnamed: 26                  35964
discovery_facility               0
dtype: int64

### Dataset Cleaning and Filtering

In [314]:
#deleting uneeded columns
del dataset['num_of_stars']

In [315]:
del dataset['num_of_planets']

In [316]:
del dataset['stellar_metallicity']

In [317]:
del dataset['stellar_metallicity_ratio']

In [318]:
del dataset['discovery_year']

In [319]:
del dataset['last_update_date']

In [320]:
del dataset['ref_pub_date']

In [321]:
del dataset['discovery_facility']

In [322]:
del dataset['Unnamed: 26']

In [323]:
# checking if columns deleted
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35964 entries, 0 to 35963
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   planet_name               35964 non-null  object
 1   host_star_name            35964 non-null  object
 2   orbital_period_day        32854 non-null  float64
 3   orbit_semi_major_axis_au  19736 non-null  float64
 4   planet_rad_earth_rad      24449 non-null  float64
 5   planet_rad_jup_rad        11331 non-null  float64
 6   planet_mass_earth_mass    5902 non-null   float64
 7   planet_mass_jup_mass      5901 non-null   float64
 8   Eccentricity              17997 non-null  float64
 9   planet_equil_temp_k       16227 non-null  float64
 10  spectral_type             2574 non-null   object
 11  stellar_effective_temp_k  33081 non-null  float64
 12  stellar_rad_solar_rad     33110 non-null  float64
 13  stellar_mass_solar_mass   30410 non-null  float64
 14  distance_parsec           35133 non-null  float64
 15  stellar_surf_grav         29308 non-null  float64
 16  declination_deg           35964 non-null  float64
 17  discovery_method          35964 non-null  object
 18  solution_type             35964 non-null  object
dtypes: float64(14), object(5)
memory usage: 5.2+ MB

In [324]:
dataset.head(10)

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method,solution_type
0,11 Com b,11 Com,NaN,1.210,NaN,NaN,5434.70000,17.100,NaN,NaN,NaN,NaN,NaN,2.60,93.1846,NaN,17.793252,Radial Velocity,Published Confirmed
1,11 Com b,11 Com,326.03000,1.290,NaN,NaN,6165.60000,19.400,0.231,NaN,G8 III,4742.0,19.00,2.70,93.1846,2.31,17.793252,Radial Velocity,Published Confirmed
2,11 Com b,11 Com,323.21000,1.178,NaN,NaN,4914.89849,15.464,0.238,NaN,G8 III,4874.0,13.76,2.09,93.1846,2.45,17.793252,Radial Velocity,Published Confirmed
3,11 UMi b,11 UMi,516.21997,1.530,NaN,NaN,4684.81420,14.740,0.080,NaN,NaN,4213.0,29.79,2.78,125.3210,1.93,71.823943,Radial Velocity,Published Confirmed
4,11 UMi b,11 UMi,NaN,1.510,NaN,NaN,3432.40000,10.800,NaN,NaN,NaN,NaN,NaN,1.70,125.3210,NaN,71.823943,Radial Velocity,Published Confirmed
5,11 UMi b,11 UMi,516.22000,1.540,NaN,NaN,3337.07000,10.500,0.080,NaN,K4 III,4340.0,24.08,1.80,125.3210,1.60,71.823943,Radial Velocity,Published Confirmed
6,14 And b,14 And,186.76000,0.775,NaN,NaN,1131.15130,3.559,0.000,NaN,K0 III,4888.0,11.55,1.78,75.4392,2.55,39.235837,Radial Velocity,Published Confirmed
7,14 And b,14 And,NaN,0.680,NaN,NaN,1017.00000,3.200,NaN,NaN,NaN,NaN,NaN,1.20,75.4392,NaN,39.235837,Radial Velocity,Published Confirmed
8,14 And b,14 And,185.84000,0.830,NaN,NaN,1525.50000,4.800,0.000,NaN,K0 III,4813.0,11.00,2.20,75.4392,2.63,39.235837,Radial Velocity,Published Confirmed
9,14 Her b,14 Her,1773.40000,2.770,NaN,NaN,1474.67000,4.640,0.369,NaN,K0 V,NaN,NaN,NaN,17.9323,NaN,43.816362,Radial Velocity,Published Confirmed

In [325]:
# filtering out exoplanets which are not confirmed
filtered_dataset = dataset[dataset['solution_type'] != 'TESS Project Candidate']
filtered_dataset

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method,solution_type
0,11 Com b,11 Com,NaN,1.210,NaN,NaN,5434.70000,17.100,NaN,NaN,NaN,NaN,NaN,2.60,93.1846,NaN,17.793252,Radial Velocity,Published Confirmed
1,11 Com b,11 Com,326.03000,1.290,NaN,NaN,6165.60000,19.400,0.231,NaN,G8 III,4742.0,19.00,2.70,93.1846,2.31,17.793252,Radial Velocity,Published Confirmed
2,11 Com b,11 Com,323.21000,1.178,NaN,NaN,4914.89849,15.464,0.238,NaN,G8 III,4874.0,13.76,2.09,93.1846,2.45,17.793252,Radial Velocity,Published Confirmed
3,11 UMi b,11 UMi,516.21997,1.530,NaN,NaN,4684.81420,14.740,0.080,NaN,NaN,4213.0,29.79,2.78,125.3210,1.93,71.823943,Radial Velocity,Published Confirmed
4,11 UMi b,11 UMi,NaN,1.510,NaN,NaN,3432.40000,10.800,NaN,NaN,NaN,NaN,NaN,1.70,125.3210,NaN,71.823943,Radial Velocity,Published Confirmed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35959,ups And d,ups And,1319.00000,2.570,NaN,NaN,1255.38000,3.950,0.269,NaN,NaN,NaN,NaN,NaN,13.4054,NaN,41.403815,Radial Velocity,Published Confirmed
35960,ups Leo b,ups Leo,385.20000,1.180,NaN,NaN,162.09249,0.510,0.320,NaN,G9 III,4836.0,11.22,1.48,52.5973,2.46,-0.823564,Radial Velocity,Published Confirmed
35961,xi Aql b,xi Aql,NaN,0.580,NaN,NaN,642.00000,2.020,NaN,NaN,NaN,NaN,NaN,1.40,56.1858,NaN,8.461105,Radial Velocity,Published Confirmed
35962,xi Aql b,xi Aql,136.75000,0.680,NaN,NaN,890.00000,2.800,0.000,NaN,NaN,4780.0,12.00,2.20,56.1858,2.66,8.461105,Radial Velocity,Published Confirmed
35963,xi Aql b,xi Aql,136.97000,0.625,NaN,NaN,616.90494,1.941,0.059,NaN,K0 III,4841.0,10.86,1.74,56.1858,2.61,8.461105,Radial Velocity,Published Confirmed

In [326]:
# checking if rows were filtered out
print(f'orignal dataset dimensions: {dataset.shape}')
print(f'filtered dataset dimesions: {filtered_dataset.shape}')

orignal dataset dimensions: (35964, 19)
filtered dataset dimesions: (34999, 19)

In [327]:
# deleting solution_type column
del filtered_dataset['solution_type']

In [328]:
#checking if column deleted
filtered_dataset.head(10)

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,NaN,1.210,NaN,NaN,5434.70000,17.100,NaN,NaN,NaN,NaN,NaN,2.60,93.1846,NaN,17.793252,Radial Velocity
1,11 Com b,11 Com,326.03000,1.290,NaN,NaN,6165.60000,19.400,0.231,NaN,G8 III,4742.0,19.00,2.70,93.1846,2.31,17.793252,Radial Velocity
2,11 Com b,11 Com,323.21000,1.178,NaN,NaN,4914.89849,15.464,0.238,NaN,G8 III,4874.0,13.76,2.09,93.1846,2.45,17.793252,Radial Velocity
3,11 UMi b,11 UMi,516.21997,1.530,NaN,NaN,4684.81420,14.740,0.080,NaN,NaN,4213.0,29.79,2.78,125.3210,1.93,71.823943,Radial Velocity
4,11 UMi b,11 UMi,NaN,1.510,NaN,NaN,3432.40000,10.800,NaN,NaN,NaN,NaN,NaN,1.70,125.3210,NaN,71.823943,Radial Velocity
5,11 UMi b,11 UMi,516.22000,1.540,NaN,NaN,3337.07000,10.500,0.080,NaN,K4 III,4340.0,24.08,1.80,125.3210,1.60,71.823943,Radial Velocity
6,14 And b,14 And,186.76000,0.775,NaN,NaN,1131.15130,3.559,0.000,NaN,K0 III,4888.0,11.55,1.78,75.4392,2.55,39.235837,Radial Velocity
7,14 And b,14 And,NaN,0.680,NaN,NaN,1017.00000,3.200,NaN,NaN,NaN,NaN,NaN,1.20,75.4392,NaN,39.235837,Radial Velocity
8,14 And b,14 And,185.84000,0.830,NaN,NaN,1525.50000,4.800,0.000,NaN,K0 III,4813.0,11.00,2.20,75.4392,2.63,39.235837,Radial Velocity
9,14 Her b,14 Her,1773.40000,2.770,NaN,NaN,1474.67000,4.640,0.369,NaN,K0 V,NaN,NaN,NaN,17.9323,NaN,43.816362,Radial Velocity

In [329]:
# creating copy of dataset
new_dataset = filtered_dataset.copy()

In [330]:
new_dataset.head(10)

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,NaN,1.210,NaN,NaN,5434.70000,17.100,NaN,NaN,NaN,NaN,NaN,2.60,93.1846,NaN,17.793252,Radial Velocity
1,11 Com b,11 Com,326.03000,1.290,NaN,NaN,6165.60000,19.400,0.231,NaN,G8 III,4742.0,19.00,2.70,93.1846,2.31,17.793252,Radial Velocity
2,11 Com b,11 Com,323.21000,1.178,NaN,NaN,4914.89849,15.464,0.238,NaN,G8 III,4874.0,13.76,2.09,93.1846,2.45,17.793252,Radial Velocity
3,11 UMi b,11 UMi,516.21997,1.530,NaN,NaN,4684.81420,14.740,0.080,NaN,NaN,4213.0,29.79,2.78,125.3210,1.93,71.823943,Radial Velocity
4,11 UMi b,11 UMi,NaN,1.510,NaN,NaN,3432.40000,10.800,NaN,NaN,NaN,NaN,NaN,1.70,125.3210,NaN,71.823943,Radial Velocity
5,11 UMi b,11 UMi,516.22000,1.540,NaN,NaN,3337.07000,10.500,0.080,NaN,K4 III,4340.0,24.08,1.80,125.3210,1.60,71.823943,Radial Velocity
6,14 And b,14 And,186.76000,0.775,NaN,NaN,1131.15130,3.559,0.000,NaN,K0 III,4888.0,11.55,1.78,75.4392,2.55,39.235837,Radial Velocity
7,14 And b,14 And,NaN,0.680,NaN,NaN,1017.00000,3.200,NaN,NaN,NaN,NaN,NaN,1.20,75.4392,NaN,39.235837,Radial Velocity
8,14 And b,14 And,185.84000,0.830,NaN,NaN,1525.50000,4.800,0.000,NaN,K0 III,4813.0,11.00,2.20,75.4392,2.63,39.235837,Radial Velocity
9,14 Her b,14 Her,1773.40000,2.770,NaN,NaN,1474.67000,4.640,0.369,NaN,K0 V,NaN,NaN,NaN,17.9323,NaN,43.816362,Radial Velocity

### Creating Program to Remove Duplicates of Exoplanets

In [333]:
# import stats from scipy to calculate mode
from scipy import stats

# creating function to get the mode of a series
# this custom mode function can help avoid a KeyError: 0
# this error can occur if the serires that is passed in the mode function is empty or there is is an isue accessing the mode_value
def mode(series):
    # handling a series if it is empty (contains null values)
    if series.empty:
        # return a null value if the series is empty
        return np.nan
    # compute mode result which is the most frequent value (mode) of the series
    mode_value = series.mode()
    # checking if mode result is empty
    if mode_value.empty:
        # return a null value if mode result result is empty
        return np.nan
    # if there are multple modes, ensuring first element is picked and if there is only one mode, then only that mode is picked
    return mode_value.iloc[0]

In [334]:
# creating a custom aggregration which uses the mean for numerical columns and the custom mode function for non-numerical columns
custom_aggregation = {
    'host_star_name': mode,
    'orbital_period_day': 'mean',
    'orbit_semi_major_axis_au': 'mean',
    'planet_rad_earth_rad': 'mean',
    'planet_rad_jup_rad': 'mean',
    'planet_mass_earth_mass': 'mean',
    'planet_mass_jup_mass': 'mean',
    'Eccentricity': 'mean',
    'planet_equil_temp_k': 'mean',
    'spectral_type': mode,
    'stellar_effective_temp_k': 'mean',
    'stellar_rad_solar_rad': 'mean',
    'stellar_mass_solar_mass': 'mean',
    'distance_parsec': 'mean',
    'stellar_surf_grav': 'mean',
    'declination_deg': 'mean',
    'discovery_method': mode
}

# ensuring all columns are present in the dataset
# for the columns present in the keys of custom_aggression
for column in custom_aggregation.keys():
    # if the column is not in new_dataset
    if column not in new_dataset.columns:
        # then raise a KeyError that the "column is not found in the dataset"
        raise KeyError(f"Column '{column}' not found in DataFrame")

# group by the name of exoplanet (group the values in the column by the planet_name)
# .agg(custom_aggregation) performs the spefic aggreagtion function within custom_aggregation for each column
# using .reset_index() to reset the index of new_dataset2
# planet_name is converted to the index of the new_dataset2 so .reset_index() coverts planet_name back into a column, creating default integer index
new_dataset2 = new_dataset.groupby('planet_name').agg(custom_aggregation).reset_index()

In [335]:
# checking that the dataset was filtered correctly
new_dataset2.head(10)

,planet_name,host_star_name,orbital_period_day,orbit_semi_major_axis_au,planet_rad_earth_rad,planet_rad_jup_rad,planet_mass_earth_mass,planet_mass_jup_mass,Eccentricity,planet_equil_temp_k,spectral_type,stellar_effective_temp_k,stellar_rad_solar_rad,stellar_mass_solar_mass,distance_parsec,stellar_surf_grav,declination_deg,discovery_method
0,11 Com b,11 Com,324.620000,1.226000,NaN,NaN,5505.066163,17.321333,0.234500,NaN,G8 III,4808.000,16.380000,2.463333,93.1846,2.380,17.793252,Radial Velocity
1,11 UMi b,11 UMi,516.219985,1.526667,NaN,NaN,3818.094733,12.013333,0.080000,NaN,K4 III,4276.500,26.935000,2.093333,125.3210,1.765,71.823943,Radial Velocity
2,14 And b,14 And,186.300000,0.761667,NaN,NaN,1224.550433,3.853000,0.000000,NaN,K0 III,4850.500,11.275000,1.726667,75.4392,2.590,39.235837,Radial Velocity
3,14 Her b,14 Her,1766.378417,2.814750,NaN,NaN,1642.383591,5.167625,0.362925,NaN,K0 V,5296.985,0.976667,0.927143,17.9323,4.420,43.816362,Radial Velocity
4,16 Cyg B b,16 Cyg B,799.375000,1.662833,NaN,NaN,533.514528,1.678667,0.676033,NaN,G2.5 V,5728.594,1.140000,1.016000,21.1397,4.344,50.516824,Radial Velocity
5,17 Sco b,17 Sco,578.380000,1.450000,NaN,NaN,1373.018720,4.320000,0.060000,NaN,K3 III,4157.000,25.920000,1.220000,124.9530,1.700,-11.837791,Radial Velocity
6,18 Del b,18 Del,988.075000,2.538667,NaN,NaN,3109.015380,9.782333,0.052000,NaN,G6 III,4979.500,8.650000,2.166667,76.2220,2.845,10.839138,Radial Velocity
7,1RXS J160929.1-210524 b,1RXS J160929.1-210524,NaN,330.000000,18.647,1.664,3135.750000,9.000000,NaN,1750.0,K7 V,4043.250,1.330000,0.792500,139.1350,4.000,-21.083140,Imaging
8,24 Boo b,24 Boo,30.340300,0.192000,NaN,NaN,284.933890,0.896500,0.037000,NaN,G3 IV,4854.500,11.415000,1.020000,95.9863,2.350,49.844649,Radial Velocity
9,24 Sex b,24 Sex,452.800000,1.333000,NaN,NaN,632.460000,1.990000,0.090000,NaN,NaN,5098.000,4.900000,1.540000,72.0691,3.500,-0.902400,Radial Velocity

In [336]:
new_dataset2.shape #5,630 rows (matches the number of confirmed exoplaenst which is also 5.630). 18 columns

(5630, 18)

### Saving this filtered dataset as a CSV file

In [338]:
# save dataset as a csv file
# output_file_path = 'filtered_exoplanet_dataset.csv'
# new_dataset2.to_csv(output_file_path, index=False)